//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjFinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableNPs1091761
    {
        public int 編號 { get; set; }
        public string 名稱 { get; set; }
        public string 縣市 { get; set; }
        public string 地址 { get; set; }
        public string 電話 { get; set; }
        public string 網址 { get; set; }
        public string 資源特色 { get; set; }
        public string 介紹 { get; set; }
    }
}
